# Generated by Django 4.1.7 on 2023-04-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('image', models.FileField(upload_to='productimages')),
                ('added_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product_table',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('own_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('own_email', models.EmailField(max_length=100, unique=True)),
                ('own_pwd', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'company_table',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('own_email', models.EmailField(max_length=100, unique=True)),
                ('own_pwd', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'owners_table',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_name', models.CharField(max_length=100)),
                ('reg_email', models.EmailField(max_length=100, unique=True)),
                ('reg_contactno', models.BigIntegerField(unique=True)),
                ('reg_pwd', models.CharField(max_length=100)),
                ('registrationtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'registration_table',
            },
        ),
    ]
