# Generated by Django 4.1.7 on 2023-04-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0002_company_secure_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='added_by',
            new_name='secure_key',
        ),
    ]
